name: Run Frontend Tests and Coverage

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Frontend Tests and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node.js Modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('farcaster/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install frontend dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm install --include=dev

      - name: Run frontend tests
        run: |
          make frontend-test